### ISSUE TITLE
dropping the first argument (this)

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/react-mini#4]
any downsides?

**Comment by esamattis** [comment]
Rather drop all others :)

It is the most flexible argument to have and actually is really convenient to use with object destructuring:

``` js
mini(({props: {title}}) => <h1>Title: {title}</h1>);
```

**Comment by stoeffel** [comment]
Yop, I use it this way most of the times anyway :-)

**Comment by esamattis** [comment]
I guess the obvious argument for removing it is that in reality one don't actually use anything but props with short-cut function like this. At least I haven't...

**Comment by esamattis** [comment]
Idea: Just do `(props, component)`.

Then the most common use case is the easiest and state access stays rather clean too

``` js
var Counter = mini(({className}, {setState, state:{count}}) => {
    var incCounter = () => setState({ count : count + step });

  return <span className={className}>Counter: {count}<button onClick={incCounter}>+1</button></span> 
}, { count: 10 }); // <= initialState
```

ps. Using the word "context" for the component in the docs is ambiguous because it can be confused with the `this.context` property of the component.

**Comment by stoeffel** [comment]
That looks like the best solution. Let's go with that.
