### ISSUE TITLE
Pure components?

### ISSUE THREAD

**Issue by esamattis** [stoeffel/react-mini#5]
I'd love to see support for pure components using [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html).

Maybe as a separate constructor so one could do something like

``` js
import {pureMini} from "react-mini";
```

**Comment by stoeffel** [comment]
Good idea! :+1:

**Comment by esamattis** [comment]
and the reasoning for the separate constructor is that I use pure components exclusively which would make an option param cumbersome because I would just set to always true.

**Comment by stoeffel** [comment]
SGTM.
